# Generated by Django 5.0.2 on 2024-11-08 01:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Element',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('element_type', models.CharField(choices=[('1', 'Competence'), ('2', 'Capability'), ('3', 'Process')], verbose_name='Element Type')),
                ('letter', models.IntegerField(choices=[(1, 'A'), (2, 'B'), (3, 'C'), (4, 'D'), (5, 'E'), (6, 'F'), (7, 'G'), (8, 'H'), (9, 'I'), (10, 'J'), (11, 'K'), (12, 'L'), (13, 'M'), (14, 'N'), (15, 'O'), (16, 'P'), (17, 'Q'), (18, 'R'), (19, 'S'), (20, 'T'), (21, 'U'), (22, 'V'), (23, 'W'), (24, 'X'), (25, 'Y'), (26, 'Z')], verbose_name='Letter')),
                ('name', models.CharField(max_length=250, verbose_name='Competence name')),
                ('comments', models.CharField(default='None', max_length=255, verbose_name='Comments')),
                ('eva_progress', models.IntegerField(default=0)),
                ('eva_made', models.IntegerField(default=0)),
                ('definitions', models.TextField(blank=True, default='None', max_length=2000, verbose_name='Definitions')),
                ('symptoms', models.TextField(blank=True, default='None', max_length=3000, verbose_name='Symptoms')),
                ('questions', models.TextField(blank=True, default='None', max_length=3000, verbose_name='Sample questions')),
                ('assess_one', models.TextField(blank=True, default='None', max_length=1000)),
                ('assess_two', models.TextField(blank=True, default='None', max_length=1000)),
                ('assess_three', models.TextField(blank=True, default='None', max_length=1000)),
                ('assess_four', models.TextField(blank=True, default='None', max_length=1000)),
                ('assess_five', models.TextField(blank=True, default='None', max_length=1000)),
                ('user_creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Element',
                'verbose_name_plural': 'Elements',
                'db_table': 'apps.element',
                'ordering': ('element_type', 'letter', 'name', 'created'),
            },
        ),
    ]
