# Generated by Django 5.0.2 on 2024-11-08 22:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Relation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Relation name')),
                ('total_elements', models.IntegerField(default=0)),
                ('competences', models.SmallIntegerField(default=0, verbose_name='Competences')),
                ('capabilities', models.SmallIntegerField(default=0, verbose_name='Capabilities')),
                ('processes', models.IntegerField(default=0, verbose_name='Processes')),
                ('eva_made', models.IntegerField(default=0, verbose_name='Evaluations made')),
                ('eva_progress', models.IntegerField(default=0, verbose_name='Evaluations in progress')),
                ('comments', models.CharField(default='None', max_length=255, verbose_name='Comments')),
                ('status', models.BooleanField(default=0)),
                ('user_creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Relation',
                'verbose_name_plural': 'Relations',
                'db_table': 'apps.relation',
                'ordering': ('name', 'eva_made', 'eva_progress', 'status'),
            },
        ),
    ]
