# Generated by Django 5.0.2 on 2024-11-08 22:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('apps_element', '0001_initial'),
        ('apps_relations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelationTree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('capability_number', models.CharField()),
                ('process_number', models.CharField()),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('element_type', models.SmallIntegerField()),
                ('relation_letter', models.SmallIntegerField()),
                ('relation_letter_display', models.CharField()),
                ('related_capability', models.IntegerField(blank=True, null=True)),
                ('related_competence', models.IntegerField(blank=True, null=True)),
                ('element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='element', to='apps_element.element')),
                ('relation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relation_tree', to='apps_relations.relation')),
            ],
            options={
                'db_table': 'apps.relation_tree',
                'ordering': ('relation', 'order'),
            },
        ),
    ]
