# Generated by Django 5.0.2 on 2024-11-08 22:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('apps_companies', '0001_initial'),
        ('apps_element', '0001_initial'),
        ('apps_relations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MainProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=30)),
                ('percentage', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('processes_evaluated', models.IntegerField(default=0)),
                ('finalized', models.BooleanField(default=0)),
                ('score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps_companies.company')),
                ('creator_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creator_user', to=settings.AUTH_USER_MODEL)),
                ('end_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='end_user', to=settings.AUTH_USER_MODEL)),
                ('relation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluation', to='apps_relations.relation')),
            ],
            options={
                'ordering': ('company', 'relation'),
            },
        ),
        migrations.CreateModel(
            name='DataModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('years_exporting', models.IntegerField(default=0)),
                ('plans_to_export', models.BooleanField(default=0)),
                ('export_variation', models.IntegerField(default=0)),
                ('foreign_investment', models.BooleanField(default=0)),
                ('average_years', models.IntegerField(default=0)),
                ('top_or_middle', models.IntegerField(default=0)),
                ('women_employed', models.IntegerField(default=0)),
                ('women_top_or_middle', models.IntegerField(default=0)),
                ('ceo_title', models.SmallIntegerField(default=1)),
                ('given_name', models.CharField(default='Empty', max_length=100)),
                ('family_name', models.CharField(default='Empty', max_length=100)),
                ('gender', models.SmallIntegerField(default=1)),
                ('telephone', models.CharField(default='Empty', max_length=20)),
                ('email', models.CharField(default='Empty', max_length=100)),
                ('business_position', models.CharField(default='Empty', max_length=100)),
                ('years_in_the_post', models.IntegerField(default=0)),
                ('comments', models.TextField(default='Empty', max_length=255)),
                ('evaluation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps_evaluations.evaluation')),
            ],
        ),
        migrations.CreateModel(
            name='EvaluationCapabilityScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competence', models.IntegerField()),
                ('capability', models.IntegerField()),
                ('score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('competence_weight', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('evaluation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_capability', to='apps_evaluations.evaluation')),
            ],
        ),
        migrations.CreateModel(
            name='EvaluationCompetenceScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('competence', models.IntegerField()),
                ('score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('evaluation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_competence', to='apps_evaluations.evaluation')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EvaluationScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_score', models.IntegerField(default=0)),
                ('form_number', models.IntegerField(default=0)),
                ('order', models.SmallIntegerField(default=0)),
                ('final_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('percentage_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='element_related', to='apps_element.element')),
                ('evaluation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaScore', to='apps_evaluations.evaluation')),
            ],
        ),
    ]
