# Generated by Django 5.0.2 on 2024-11-07 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Logs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('ip', models.CharField(max_length=25)),
                ('location_country', models.CharField(default='None', max_length=200)),
                ('location_city', models.CharField(default='None', max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
