# Generated by Django 5.0.2 on 2024-11-08 18:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('apps_continents', '0001_initial'),
        ('apps_regions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150, verbose_name='Country')),
                ('inhabitants', models.IntegerField(default=0)),
                ('continent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps_continents.continent')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps_regions.region')),
            ],
            options={
                'verbose_name': 'Country',
                'verbose_name_plural': 'Countries',
                'db_table': 'apps.country',
                'ordering': ('name', 'continent', 'region'),
            },
        ),
    ]
