# Generated by Django 5.0.2 on 2024-11-09 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps_countries', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='created',
        ),
        migrations.RemoveField(
            model_name='country',
            name='updated',
        ),
    ]
